
export const useMetaData = () =>{
    const handelTitle = () =>{
        return  {
            title: "Hyper movies",
            description: "Generated by create next app",
          };

    }
   return {handelTitle}
}