"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { useStoreHyperMovies } from "@/store/store";
import { useMetaData } from "@/metadata";
import { useEffect } from "react";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const image = useStoreHyperMovies((s) => s.image);
  const { handelTitle } = useMetaData();
  useEffect(() => {
    const { title, description } = handelTitle();
    document.title = title;
    const metaDescription = document.querySelector('meta[name="description"]');
    if (metaDescription) {
      metaDescription.setAttribute("content", description);
    }
  }, [handelTitle]);
  return (
    <html lang="en">
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />

      <body
        style={{ backgroundImage: `url(${image})` }}
        className={`${geistSans.variable} ${geistMono.variable}  antialiased h-screen overflow-hidden flex flex-col bg-slate-800 bg-cover bg-center bg-no-repeat  backdrop-filter backdrop-blur-sm backdrop-brightness-50 duration-300`}
      >
        {children}
      </body>
    </html>
  );
}
